language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - pytest
after_success:
  - codecov # submit coverage